### ISSUE TITLE
no shell no error message

### ISSUE THREAD

**Issue by busbauen** [gojhonny/CredCrack#10]
What could be the problem if I just got this:

root@kali:~/CredCrack# ./credcrack.py -d workgroup -r 192.168.122.237 -u Christian -l 192.168.122.25
Password: 

 ---------------------------------------------------------------------
  CredCrack v1.0 by Jonathan Broche (@g0jhonny)
 ---------------------------------------------------------------------
 
[*] Setting up the stage
[*] Validating 192.168.122.237
[*] Querying domain admin group from 192.168.122.237
[*] Cleaning up
root@kali:~/CredCrack# 

The "list shares" works. Thank you

**Comment by gojhonny** [comment]
Hey busbauen, what's the target OS?

**Comment by busbauen** [comment]
It's a Win 7 Professional x86 virtual machine. It's a fresh installation. No SP I guess

**Comment by gojhonny** [comment]
This is due to using CredCrack in a WORKSTATION environment. CredCrack stops running due to not being able to obtain a list of domain administrators. This is a bug and will be fixed in the next update. Thank you for brining this to my attention!

**Comment by gojhonny** [comment]
Hi busbauen, after giving some thought to the issue I have decided not to implement WORKSTATION support into CredCrack. The thing is, there's not really a reason for the ability to perform mass credential exfiltration on a WORKSTATION environment nor would it work well for many reasons. I hope you can see my point here, but if you'd like me to elaborate just contact me.

If you were attempting to run CredCrack within a small environment for learning purposes then I'd highly recommend breaking down the script and trying to do the extraction manually. Additonally, I also recommend downloading the binaries for (mimikatz)[http://blog.gentilkiwi.com/mimikatz] and messing around with (PowerSploit's)[https://github.com/mattifestation/PowerSploit] while you're at it. Most importantly, learn how to (defend)[http://blog.gojhonny.com/2015/08/preventing-credcrack-mimikatz-pass-hash.html] against an attack like this!

I hope this helps, don't hessitate to ping me with any questions or comments. Thanks for your feedback and for trying CredCrack!

- J
