### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Papoulos** [gojhonny/CredCrack#5]
./credcrack.py -d domain -u user  -es -r 10.10.10.1

 ---------------------------------------------------------------------
  CredCrack v1.0 by Jonathan Broche (@g0jhonny)
 ---------------------------------------------------------------------

[*] Validating 10.10.10.1
[!] Error listing shares on 10.10.10.1: [Errno 2] No such file or directory

I've always the same error whatever the options I use.
Is there a dependence i miss ?

I've try with "-F hosts"
but i got hte same message with all the IP adresses.
I've tried with a wrong password and it tells me the same...

Any idea ?
Do i need to be under Kali ?
I've a centos 7
;)

**Comment by gojhonny** [comment]
Hi Papoulos, thanks for submitting an issue! Here are some questions to better understand and tackle the issue. 
*What are the operating systems of the machines you are enumerating? 
*Do you have smbclient installed on CentOS? If so, what's the version?
  * You can obtain the version with the '''smbclient -V''' command

**Comment by Papoulos** [comment]
Ok.
Don't throw anything...
i tested it on a machine that didn't have smbclient...
Bad choice, now with the client it's OK.

And now when I tray to harvest it tells me :
"unable to reach to 10.10.10.1"

But the ping and the share enum work fine.

Hope it's not the same thing that for the first question...

Thank you.
