### ISSUE TITLE
ValueError: zero length field name in format

### ISSUE THREAD

**Issue by fenx999fight** [gojhonny/CredCrack#7]
Hello, i have an error when i execute the script:

ValueError: zero length field name in format

My python version is 2.6.6. I execute this line command:

./credcrack.py -d XXX -u XXX -f hosts -es

My exactly Error:

Traceback (most recent call last)
File "./credcrack.py", line415,
main()
File "./credcrack.py", line411, in main
print "{}[!]{} File: {} does not exist.".format'colors.red, colors.normal, args.file)
ValueError: zero length field name in format

Sorry for my bad english and thank you verymutch

**Comment by gojhonny** [comment]
Hi fenx999fight, thank you for bringing this to my attention. This is most likely due to using python 2.6. I'll push an update with field names/numbers and that should do it. Please standby.

**Comment by fenx999fight** [comment]
OK thanks you, i wait update.

**Comment by fenx999fight** [comment]
Hello,

waiting, i tried with python 2.7. Powershell file (Invoke-Mimikatz.ps1) does not download: erreur 404 not found

Next, I start the command line and it works now:

root@sexilog:/home/sexiuser# ./credcrack.py -d xxxx -u xxxxx.xxxx -f hosts -                               l 172.20.XXX.XXX
Password:

 ---------------------------------------------------------------------
  CredCrack v1.0 by Jonathan Broche (@g0jhonny)
 ---------------------------------------------------------------------

[*] Setting up the stage
[!] File: hosts does not exist.

[*] Cleaning up
root@sexilog:/home/sexiuser#

i don't understand....

**Comment by fenx999fight** [comment]
Adding the absolute path with / etc / host , I have another message


root@sexilog:/home/sexiuser# ./credcrack.py -d corp -u helpline.admin -f /etc/hosts -l 172.20.128.28
Password:

 ---------------------------------------------------------------------
  CredCrack v1.0 by Jonathan Broche (@g0jhonny)
 ---------------------------------------------------------------------

[*] Setting up the stage
[*] Validating 127.0.0.1   localhost
[!] Unable to connect to 127.0.0.1   localhost
[*] Validating sexilog
[!] Unable to connect to sexilog

[*] Cleaning up
root@sexilog:/home/sexiuser#

thanks

PS:
hould I put the IP address of a domain controller for it to work or just a member of the domain ?

**Comment by fenx999fight** [comment]
root@sexilog:/home/sexiuser# ./credcrack.py -d corp -u helpline.admin -f /etc/hosts -l 172.20.128.252
Password:

 ---------------------------------------------------------------------
  CredCrack v1.0 by Jonathan Broche (@g0jhonny)
 ---------------------------------------------------------------------

[*] Setting up the stage
[*] Validating 127.0.0.1   localhost
[!] Unable to connect to 127.0.0.1   localhost
[*] Validating 172.20.128.251 sexilog.corp.lan
[!] Unable to connect to 172.20.128.251 sexilog.corp.lan
[*] Validating 172.20.128.252 svpw-admin-gen.corp.lan
[*] Validating 172.20.128.28 dc924.corp.lan
[*] Querying domain admin group from 172.20.128.252 svpw-admin-gen.corp.lan
[!] Unable to reach to 172.20.128.252 svpw-admin-gen.corp.lan
[*] Querying domain admin group from 172.20.128.28 dc924.corp.lan
[!] Unable to reach to 172.20.128.28 dc924.corp.lan

**Comment by fenx999fight** [comment]
root@sexilog:/home/sexiuser# ./credcrack.py -d corp -u helpline.admin -f /etc/hosts -l 172.20.128.252
Password:

 ---------------------------------------------------------------------
  CredCrack v1.0 by Jonathan Broche (@g0jhonny)
 ---------------------------------------------------------------------

[*] Setting up the stage
[*] Validating 127.0.0.1   localhost
[!] Unable to connect to 127.0.0.1   localhost
[*] Validating 172.20.128.251 sexilog.corp.lan
[!] Unable to connect to 172.20.128.251 sexilog.corp.lan
[*] Validating 172.20.128.252 svpw-admin-gen.corp.lan
[*] Validating 172.20.128.28 dc924.corp.lan
[*] Querying domain admin group from 172.20.128.252 svpw-admin-gen.corp.lan
[!] Unable to reach to 172.20.128.252 svpw-admin-gen.corp.lan
[*] Querying domain admin group from 172.20.128.28 dc924.corp.lan
[!] Unable to reach to 172.20.128.28 dc924.corp.lan

**Comment by fenx999fight** [comment]
hello,

[*] Validating 172.20.128.xxx
[!] Error listing shares on 172.20.128.xxx: [Errno 2] No such file or directory

[*] Done! Completed in 0.0s

root@sexilog:/home/sexiuser#

**Comment by fenx999fight** [comment]
sorry, I had forgotten to install smbclient.... It'ok now with smbclient 3.6.6

**Comment by fenx999fight** [comment]
Now:

"""" root@sexilog:/home/sexiuser# ./credcrack.py -d corp -u administrateur -f hosts -l 172.20.128.252
Password:

 ---------------------------------------------------------------------
  CredCrack v1.0 by Jonathan Broche (@g0jhonny)
 ---------------------------------------------------------------------

[*] Setting up the stage
[*] Validating 172.20.128.252
[*] Querying domain admin group from 172.20.128.252
[!] Unable to reach to 172.20.128.252

[*] Cleaning up
root@sexilog:/home/sexiuser#   """


the script works ? it's normal ?

Yet he finds shares:

root@sexilog:/home/sexiuser# ./credcrack.py -r 172.20.128.252 -d xxxx -u xxxx -es
Password:

 ---------------------------------------------------------------------
  CredCrack v1.0 by Jonathan Broche (@g0jhonny)
 ---------------------------------------------------------------------

[*] Validating 172.20.128.252

 -----------------------------------------------------------------
 172.20.128.252 - Windows Server 2012 R2 Standard 9600
 -----------------------------------------------------------------

 OPEN      \\172.20.128.252\ADMIN$
 OPEN      \\172.20.128.252\C$
 OPEN      \\172.20.128.252\E$
 OPEN      \\172.20.128.252\HelpLine_Admin
 OPEN      \\172.20.128.252\test

[*] Done! Completed in 0.5s

root@sexilog:/home/sexiuser#


thanks you GoJhoony!

**Comment by gojhonny** [comment]
Hi fenx999fight, this is interesting since the enumerate shares functionality is working. Can you check to see if AV on your test system is catching winexe?

**Comment by fenx999fight** [comment]
Hi,
- When I attack a 2003 server with winexe, no problem (example with ipconfig):

![capture](https://cloud.githubusercontent.com/assets/13768080/9270951/0da61768-4276-11e5-931d-4fa4ead3df45.JPG)

But the command does not work:
![capture3](https://cloud.githubusercontent.com/assets/13768080/9271026/c3e7df34-4276-11e5-9a3f-107d5bfe0510.JPG)


- If i attack 2012 R2, there is a problem (invalid parameter it's another problem because it's 2012 R2):

![capture2](https://cloud.githubusercontent.com/assets/13768080/9270981/49152e42-4276-11e5-9f02-15727eda5c35.JPG)

But let's deal 2003 server, the command works with winexe but your script (creed) does not work and stops on: "UNABLE TO REACH"

Thanks.

**Comment by fenx999fight** [comment]
Now with yout last version creedcrack.py i have a new problem:

![capture4](https://cloud.githubusercontent.com/assets/13768080/9271439/3a518b86-427a-11e5-8029-8f6d72cf7890.JPG)

**Comment by fenx999fight** [comment]
I am on vacation 2 weeks, then I'll come back here.

Thanks you.

**Comment by riahc3** [comment]
I might be completely wrong but...

I see that you are using another language of Windows, more so one that has accents.

Sometimes (more so Windows side) there are problems when getting/pushing text so CredCrack might be getting a incomplete string and interpreting it as something else.

**Comment by gojhonny** [comment]
The next update should improve CredCrack's stability thus fixing the Windows 2003 bug. I am also currently testing methods to implement CredCrack on Windows 10 and Server 2012. Please standby and thank you for your feedback!

**Comment by gojhonny** [comment]
Hi fenx999fight, what version of PowerShell is Server 2003 running?

**Comment by fenx999fight** [comment]
Hi, i use Powershell version 4.0 and Windows 2003 R2 Standard Edition. I re-run with v1.1 and coming back to you. Thanks.

**Comment by fenx999fight** [comment]
It's the same thing :
![top](https://cloud.githubusercontent.com/assets/13768080/9545649/2c1c1514-4d8c-11e5-9994-40c9130a0180.JPG)

**Comment by gojhonny** [comment]
Let's try some manual testing. Can you please try the following command? Thanks!

`winexe --system //172.20.x.x -U domain/user%pass 'cmd /c net group "Domain Admins" /domain'`

**Comment by gojhonny** [comment]
No reply in over two weeks. Closing assuming this has been resolved.
