### ISSUE TITLE
Running the script does nothing in Kali Linux

### ISSUE THREAD

**Issue by riahc3** [gojhonny/CredCrack#8]
I try running the script after setting it up and it seems not to do anything. Thats OK but I think a message saying what went wrong would be better.

![k](https://cloud.githubusercontent.com/assets/1131521/9244212/6d76aaaa-4199-11e5-86c0-e21fc2108c10.png)

**Comment by gojhonny** [comment]
Hi riahc3, thanks for bringing this to my attention. The issue comes from not supplying either an rhost [-r] or file [-f] with hosts to target. I have improved parameter checking with the latest release and this should be fixed. Thank you!
