### ISSUE TITLE
Unable tor reach

### ISSUE THREAD

**Issue by reversingfr** [gojhonny/CredCrack#9]
Hi 
thank you for you great work.

I've got this error when a use the credcrack.py

root@kali:~/Downloads/CredCrack-master# ./credcrack.py -d domaine -u user -f ip -l 10.247.192.217Password: 

 ---------------------------------------------------------------------
  CredCrack v1.0 by Jonathan Broche (@g0jhonny)
 ---------------------------------------------------------------------
 
[*] Setting up the stage
[*] Validating 10.247.192.200
[*] Validating 10.247.192.192
[*] Validating 10.247.192.182
[*] Querying domain admin group from 10.247.192.200
[!] Unable to reach to 10.247.192.200
[*] Querying domain admin group from 10.247.192.192
[!] Unable to reach to 10.247.192.192
[*] Querying domain admin group from 10.247.192.182
[!] Unable to reach to 10.247.192.182

do you have any idea how to resolv this please ?

thank you !

**Comment by fenx999fight** [comment]
I had the same problem as I had not installed smbclient....if this can help you

**Comment by gojhonny** [comment]
reversingfr, what version of Kali are you running? Use `cat /etc/issue` to see the verison

**Comment by reversingfr** [comment]
Hi ! thank you for you reply

- I use Kali version 1.1.0 (Kali GNU/Linux 1.1.0 \n \l)

- I have administrative access to the system

- the command line : ./credcrack.py -d domaine.fr -u administrateur -f ip -es  works great

thank you

**Comment by gojhonny** [comment]
What are the operating systems of the systems you are testing against?

**Comment by reversingfr** [comment]
Windows 2008 R2 64 bits (exchange system + AD)

**Comment by gojhonny** [comment]
reversingfr, were you able to figure it out since you closed the issue?

**Comment by reversingfr** [comment]
no sorry, missclick :/

**Comment by gojhonny** [comment]
No problem! Do you have AV on the machines? If you do, check to see if winexe is getting flagged. It's very rare but in some cases AV can flag winexe.

**Comment by reversingfr** [comment]
I've just download the last version of you credcrack.py, and launch this command line 

-./credcrack.py -d domaine.fr -u administrateur -f ip -l 10.247.192.217

Password: 

 ---------------------------------------------------------------------
  CredCrack v1.0 by Jonathan Broche (@g0jhonny)
 ---------------------------------------------------------------------
 
[*] Setting up the stage
[*] Validating 10.247.192.200
[*] Validating 10.247.192.192
[*] Querying domain admin group from 10.247.192.200
[*] Querying domain admin group from 10.247.192.192
[*] Cleaning up


Don't have the unable to reach error. But don't find anything

(no AV on theses machines)

**Comment by Papoulos** [comment]
I've DL the new version uploaded 10h from now and it's the new message i got 

credcrack.py -d domain -u user-l 10.10.1.10 -r 10.10.1.1

 ---------------------------------------------------------------------
  CredCrack v1.0 by Jonathan Broche (@g0jhonny)
 ---------------------------------------------------------------------

[*] Setting up the stage
[*] Validating 192.168.144.5
[*] Querying domain admin group from 10.10.1.1
[!] Unable to reach to 10.10.1.1

Traceback (most recent call last):
  File "./credcrack.py", line 429, in <module>
    main()
  File "./credcrack.py", line 382, in main
    if "NT_STATUS_LOGON_FAILURE" in das:
TypeError: argument of type 'bool' is not iterable

I've tried diffent domain names but it's all the same...

**Comment by lstep** [comment]
Yes, that's a bug. The `get_das` method is supposed to return a list, but it will return either a string (when failed to logon), either a bool (when there is an exception, your case), either a list if all goes OK.
That method should be made more consistent as the returning value is just checked against a list, which fails in case of error in that method...

**Comment by gojhonny** [comment]
Hey guys, hold tight. Brainstorming possible ways to improve and implement a beter `get_das` function. Thank you for your comments and feedback!

**Comment by gojhonny** [comment]
reversingfr,

What were the results of the enumerate shares function when you ran it? Systems that reflect an OPEN status on the C drive mean you have administrative access, otherwise you don't thus CredCrack won't be able to work properly.

**Comment by gojhonny** [comment]
Closing issue assuming it has been resolved. No response received in over 20 days.
